# Generated by Django 4.1.2 on 2022-10-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('modification', models.CharField(max_length=20)),
                ('horse_powers', models.PositiveIntegerField()),
            ],
        ),
    ]
