# Generated by Django 4.1.2 on 2022-10-18 12:44

from django.db import migrations, models
import forms_demos_mine.departments.validators


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclecar',
            name='horse_powers',
            field=models.IntegerField(validators=[forms_demos_mine.departments.validators.validator_for_a_muscle_car]),
        ),
    ]
