# Generated by Django 4.1.2 on 2022-10-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_musclecar_horse_powers'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclecar',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
