# Generated by Django 4.1.2 on 2022-10-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_musclecar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclecar',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
